#!/usr/bin/python
#-*- coding:utf-8 -*-

config = {
    'properties': {
        u'Denumire': ('', None, 'label'),
        u'Coord': ('P625', False, 'globe-coordinate'),
        u'imagine': ('P18', True, 'commonsMedia'),
        u'hartă': ('P242', False, 'commonsMedia'),
        u'colaj': ('P2716', True, 'commonsMedia'),
        u'video': ('P10', True, 'commonsMedia'),
        u'Țară': ('P17', False, 'wikibase-item'),
        u'Commons': ('P373', False, 'string'),
        u'SIRUTA': ('P843', False, 'string'),
        u'este un/o': ('P31', False, 'wikibase-item'),
        u'subdiviziuni': ('P1383', False, 'wikibase-item'),
        u'localități componente': ('P1383', False, 'wikibase-item'),
        u'fus orar': ('P421', False, 'wikibase-item'),
        u'primar': ('P6', False, 'wikibase-item'),
        u'codp': ('P281', True, 'string'),
        u'SIRUTASUP': ('P131', False, 'wikibase-item'),
        u'ISO3166-2': ('P300', False, 'string'),
        u'populație': ('P1082', False, 'quantity'),
        u'suprafață': ('P2046', False, 'quantity'),
        u'reședință pentru': ('P1376', False, 'wikibase-item'),
        u'site': ('P856', False, 'url'),
        u'stemă': ('P94', False, 'commonsMedia'),
        u'drapel': ('P41', False, 'commonsMedia'),
    },
	'counties': [
		'Alba',
		'Arad',
		'Argeș',
		'Bacău',
		'Bihor',
		'Bistrița-Năsăud',
		'Botoșani',
		'Brașov',
		'Brăila',
		'Buzău',
		'Caraș-Severin',
		'Călărași',
		'Cluj',
		'Constanța',
		'Covasna',
		'Dâmbovița',
		'Dolj',
		'Galați',
		'Giurgiu',
		'Gorj',
		'Harghita',
		'Hunedoara',
		'Ialomița',
		'Iași',
		'Ilfov',
		'Maramureș',
		'Mehedinți',
		'Mureș',
		'Neamț',
		'Olt',
		'Prahova',
		'Satu Mare',
		'Sălaj',
		'Sibiu',
		'Suceava',
		'Teleorman',
		'Timiș',
		'Tulcea',
		'Vaslui',
		'Vâlcea',
		'Vrancea'
	]
}

all_counties = config['counties'] + ['București']